### PR TITLE
Added ability to remove background operations

### PR DESCRIPTION
**Pull request by MirkoSc**
I need the ability to dynamically add/remove background operations based on the configuration.

### CODE REVIEW

**Comment by CraigHawker** [comment]
Should removing a background operation implicitly cancel all future executions?  Otherwise you may end up with some odd errors when a future execution then comes to be processed.

I feel that cancelling future executions should be the default behaviour.  If there are some situations where the background operation should be removed but the future execution kept (e.g. for replacing it, perhaps), then I feel this should be an explicit operation by the developer.

Perhaps the method signature should be:

```
public bool RemoveBackgroundOperation
		(
			string name,
			bool cancelFutureExecutions = true
		)
```

What are your thoughts?

Regards,

Craig.

**Comment by MirkoSc** [comment]
Thats a good point, i didn't thought about it, because i cancled the operation in my code before.

I've checked what happens if I remove the background operation without canceling it before.
The result is that once the background operation is removed, it is not called again.
So do we really need this additional parameter?

I also added the ability to get the background operation name from the task processor job.
With this functionality i can check which background operation called the method.
Last but not least I added the ability to get the names of all background operations and a specific background operation by name from the background operation manager.

Now I can dynamically create/update/delete background operations based on some configuration settings.

Regards,
Mirko

**Comment by CraigHawker** [comment]
I would need to check it, but I believe that removing the background operation will cause any future execution of that task to fail.  An exception would be written to the event log as the task would be loaded but it would not be able to find the background operation that is supposed to run it.  That would occur here: https://github.com/M-Files/VAF.Extensions.Community/blob/master/MFiles.VAF.Extensions/TaskQueueBackgroundOperations/TaskQueueBackgroundOperationManager/TaskQueueBackgroundOperationManager.cs#L222

It is only a single error - I don't think there'll be any other knock-on effects - but it's still something that I feel should be handled more gracefully by simply cancelling any future executions so that this doesn't happen.

**Comment by MirkoSc** [comment]
I've added the ability to get the internal directive of an application task of the BackgroundOperationTaskQueueDirective type of directive. I need this because the BackgroundOperationTaskQueueDirective type isn't public. 

I also checked the problem with future executions of a background operation. I found out that the application tasks never get canceled unless we cancel it in the task processor like here https://github.com/M-Files/VAF.Extensions.Community/blob/2498eda292d7f8ef428a3381d5d2e3caff128625/MFiles.VAF.Extensions/TaskQueueBackgroundOperations/TaskQueueBackgroundOperation.cs#L445.
Because there is currently no way to replace a background operation, it doesn't make sense to have a optional parameter for it.
So I added the cancel all future executions function to the remove background operations function.

Do you have any other concerns?
I've added the ability to get the internal directive of an application task of the BackgroundOperationTaskQueueDirective type of directive.

I also checked the problem with future executions of a background operation. I found out that the application tasks never get canceled unless we cancel it in the task processor like here https://github.com/M-Files/VAF.Extensions.Community/blob/2498eda292d7f8ef428a3381d5d2e3caff128625/MFiles.VAF.Extensions/TaskQueueBackgroundOperations/TaskQueueBackgroundOperation.cs#L445.
Because there is currently no way to replace a background operation, it doesn't make sense to have a optional parameter for it.
So I added the cancel all future executions function to the remove background operations function.

Do you have any other concerns?
I would be happy if the changes are included in the next version. I currently have to work with a local version.

Regards,
Mirko

Regards,
Mirko

**Review by CraigHawker — APPROVED** [review]
Looking good!

I have a slight concern about `TaskProcessorJobEx.TaskQueueBackgroundOperationName` getter calling `GetTaskQueueDirective` (a getter implies that it's quick to read, whereas this has some obscure overhead), but let's deal with that separately.

Thank you for the PR!

**Pull request merged**
