### PR TITLE
Testing actions

### PR DESCRIPTION
**Pull request by CraigHawker**
Added github actions:
1. Forced basic build step on pull request to master/main, and to pushes to the same branches.
2. On push to release/prerelease: Create appropriate version string, force build, push to nuget, create release, upload nupkg

Unfortunately we can't run the unit tests as the runner doesn't have M-Files installed.

### CODE REVIEW

**Comment by ysn-wtag** [comment]
> Added github actions:
> 
> 1. Forced basic build step on pull request to master/main, and to pushes to the same branches.
> 2. On push to release/prerelease: Create appropriate version string, force build, push to nuget, create release, upload nupkg
> 
> Unfortunately we can't run the unit tests as the runner doesn't have M-Files installed.

Can't we still run unit tests? 

While trying to run unit tests in github action, we get - `System.Runtime.InteropServices.COMException : Retrieving the COM class factory for component with CLSID ........ failed due to the following error: Class not registered.`

**Comment by CraigHawker** [comment]
Not with public runners, unfortunately.

**Comment by ysn-wtag** [comment]
> Not with public runners, unfortunately.

In which runner it's possible then?

**Comment by CraigHawker** [comment]
In your own fork you should be able to use private runners. This is not something we've investigated thoroughly due to the documented security concerns (github has an article or two).

**Comment by ysn-wtag** [comment]
Our repo is private and we get the same error stated above.

**Comment by CraigHawker** [comment]
I think you misunderstand.

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners

**Comment by ysn-wtag** [comment]
> I think you misunderstand.
> 
> https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners

Oh, got it now. So for GitHub hosted runners there is no option to run unit tests, right?

**Comment by CraigHawker** [comment]
The github hosted runners do not have M-Files installed, which is a prerequisite for using the API. So no.

**Comment by ysn-wtag** [comment]
Is there any way to install M-Files into GitHub hosted runners?

**Comment by CraigHawker** [comment]
Not to my knowledge.

If you wish to continue this discussion then please use the forum.

**Pull request merged**
